TAXI-54 car entity wired up to user
CodecoolBP20161/advanced-module-neightbro-taxi pull request #38
Opened 2017-02-21 08:32 UTC by kalmeee

TAXI-53 and TAXI-54

2017-02-21 09:07 UTC, annamatolay approved these changes

2017-02-21 10:50 UTC, beru26 approved these changes

2017-02-21 11:26 UTC, horada1991 requested changes
Why ManyToMany connection? I think one car doesn't have many owners. Just one. so its a onetomany on the user side.

2017-02-25 14:22 UTC, horada1991 approved these changes

2017-02-27 09:48 UTC, davidfeher approved these changes

2017-02-27 09:49 UTC, merged